services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    UniversignRest\ClientBundle\:
        resource: '../../*'
        exclude: '../../{Event,Entity,Exception,Model}'

    default_universign_rest_client:
        class: UniversignRest\ClientComponent\Service\UniversignClient
        autowire: true
        arguments:
            $uri: '%universign_rest_uri%'
            $token: '%universign_rest_token%'
            $logger: '@monolog.logger.universign'

    UniversignRest\ClientComponent\Service\UniversignClientInterface: '@default_universign_rest_client'
