services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Universign\ClientBundle\:
        resource: '../../*'
        exclude: '../../{Event,Entity,Exception,Model}'

    default_universign_rest_client:
        class: Universign\Rest\ClientComponent\Service\UniversignClient
        autowire: true
        arguments:
            $uri: '%universign_uri%'
            $token: '%universign_token%'
            $logger: '@monolog.logger.universign'

    Universign\Rest\ClientComponent\Service\UniversignClientInterface: '@default_universign_rest_client'